### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by heshesh2010** [chinloyal/pusher_client#16]
VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method init on channel com.github.chinloyal/pusher_client)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
#2      PusherClient._init (package:pusher_client/src/pusher/pusher_client.dart:61:20)
#3      new PusherClient (package:pusher_client/src/pusher/pusher_client.dart:52:16)
#4      _chatState.initState (package:adalah/screens/chat.dart:20:27)
#5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
#9      SingleChildRenderObjectElement.mount (package:fl<…>
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method connect on channel com.github.chinloyal/pusher_client)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
#2      PusherClient.connect (package:pusher_client/src/pusher/pusher_client.dart:92:20)
#3      _chatState.initState (package:adalah/screens/chat.dart:27:12)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
#6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
#8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
#9      Element.inflateWidget (package<…>

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.3 20D91 darwin-x64, locale en-EG)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by brunodelsing** [comment]
Restarting your app should fix this.

**Comment by chinloyal** [comment]
@heshesh2010 Were you able to resolve this?
