### ISSUE TITLE
No implementation found for method init on channel com.github.chinloyal/pusher_client

### ISSUE THREAD

**Issue by wahid8080** [chinloyal/pusher_client#44]
Unhandled Exception: MissingPluginException(No implementation found for method init on channel com.github.chinloyal/pusher_client)
E/flutter ( 1715): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter ( 1715): <asynchronous suspension>
E/flutter ( 1715): #1      PusherClient._init (package:pusher_client/src/pusher/pusher_client.dart:61:5)
E/flutter ( 1715): <asynchronous suspension>
E/flutter ( 1715):

**Comment by osbre** [comment]
Solution: restart the app.
https://github.com/chinloyal/pusher_client/issues/16#issuecomment-826716855
